### ISSUE TITLE
Awesome... but one problem

### ISSUE THREAD

**Issue by ajxanman** [LegendofthePlaidDragon/LegendofthePlaidDragon.github.io#1]
This is an awesome site! But the slack button doesn't work. When you click on it, it shows the following error: "OAuth Error: invalid_client_id" I'm not sure what that means, but just something to think about!

**Comment by Ntangen** [comment]
Hey! Yes, I know - I disabled the app for the time being. Too many requests coming in. I might gin it up later, though!
